In [317]:
import numpy as np
import math

A = np.zeros(shape=(3,2))
mu, sigma = 0, 0.1 # mean and standard deviation
for i in range(A.shape[0]):
    for j in range(A.shape[1]):
        A[i][j] = np.random.normal(mu, sigma, 1)
print("Matrix A:")
print(A)
print("Rank of Matrix A: ", np.linalg.matrix_rank(A))

Matrix A:
[[ 0.04075344 -0.09264863]
 [ 0.10914279  0.05894637]
 [ 0.03424502  0.04106398]]
Rank of Matrix A:  2


In [318]:
N = 500
v = np.zeros(shape=(2,1))
X = np.zeros(shape=(3,N))
x = np.zeros(shape=(3,1))
for i in range(N):
    v[0] = np.random.normal(mu, sigma, 1)
    v[1] = np.random.normal(mu, sigma, 1)
    x = np.matmul(A, v)
    X[0][i] = x[0]
    X[1][i] = x[1]
    X[2][i] = x[2]
print("Shape of Matrix X: ", X.shape)
print("Rank of Matrix X: ", np.linalg.matrix_rank(X))

Shape of Matrix X:  (3, 500)
Rank of Matrix X:  2


In [319]:
u, s, vT = np.linalg.svd(X)
print("Matrix U: columns are the left singular vectors")
print(u)
XXT = np.matmul(X, X.transpose())
w, v = np.linalg.eig(XXT)
XTX = np.matmul(X.transpose(), X)
w2, v2 = np.linalg.eig(XTX)
print("Matrix v: columns are the eigenvectors")
print(v)

Matrix U: columns are the left singular vectors
[[ 0.21388132  0.96003226  0.1805349 ]
 [-0.8960249   0.26641574 -0.35519294]
 [-0.38909402 -0.08579463  0.91719416]]
Matrix v: columns are the eigenvectors
[[ 0.21388132 -0.96003226  0.1805349 ]
 [-0.8960249  -0.26641574 -0.35519294]
 [-0.38909402  0.08579463  0.91719416]]


In [320]:
print("the singular values")
# A = np.zeros(shape=(3,2))
print(s)
for i in range(3):
    w[i] = math.sqrt(w[i])
print()
print(w)

the singular values
[  3.20759437e-01   2.28455202e-01   1.97141032e-17]

[  3.20759437e-01   2.28455202e-01   1.70342288e-09]


In [321]:
print("The Frobenius norm is equal to the sum of the squares of the singular values")
print(np.linalg.norm(X)**2)
print(s[0]**2+s[1]**2+s[2]**2)

The Frobenius norm is equal to the sum of the squares of the singular values
0.155078396057
0.155078396057


Since the rank of X is two, there should only be two nonzero singular values of X. But in most cases this doesn't happen instead the numbers just get really close to zero this is because of floating point errors in python.

### PCA of Dataset #1

1) even though we can have up to three principal components, two principal components should be enough to capture all variation in the data because of the way matrix X was generated. Each column was computed by multiplying A (a fixed matrix) and v which is a random 2 x 1 matrix. So in each column only two values varied.

In [322]:
print(X)
print(X[2][0])

[[-0.01238421 -0.001487   -0.01363596 ...,  0.01075637 -0.00283135
  -0.01017508]
 [-0.00975347  0.00601872  0.00605433 ...,  0.0085605  -0.01322485
   0.01015058]
 [-0.0013395   0.0026235   0.00502862 ...,  0.00119792 -0.00456415
   0.00593372]]
-0.00133949801392


In [323]:
meanVector = np.zeros(shape=(1,500))

for i in range(X.shape[1]): 

    mean = 0.00; 

    sum = 0; 

    for j in range(X.shape[0]): 
        sum = sum + X[j][i]

    mean = sum / X.shape[0]
    meanVector[0][i] = mean

print("This is the mean vector of matrix X with very small entries.")
print()
print(meanVector)

This is the mean vector of matrix X with very small entries.

[[ -7.82572472e-03   2.38507137e-03  -8.51002060e-04  -1.23129760e-02
    8.56470636e-04  -9.56235769e-03  -9.17920248e-03  -5.18877052e-03
   -4.53975230e-03   8.75064372e-03  -1.67359204e-03  -7.50560400e-03
    3.83678502e-03  -5.06928178e-03   1.47945308e-03   6.52922763e-03
    1.89665790e-03   4.03507652e-03  -7.06062439e-03  -6.71194054e-05
   -3.21592613e-03  -1.01591945e-02   2.10178404e-03  -9.79942697e-03
   -6.49113388e-03  -1.36436001e-03   2.62716524e-03   6.05478464e-03
    6.72460901e-03   1.66037707e-02  -2.02338739e-03  -2.77198648e-03
   -6.04893126e-03  -3.01882488e-03  -2.77974389e-03  -4.65752406e-03
   -3.82213658e-03  -6.73516551e-03  -9.85976558e-03  -2.52995693e-03
   -6.55607523e-03   8.11471727e-03  -5.04494169e-03  -6.81207316e-03
   -6.86370697e-03  -1.08246898e-02  -1.43666272e-03  -2.35876138e-03
    3.57554219e-03  -5.89250418e-03  -6.90596331e-03   3.41267932e-03
    4.85111850e-03   2.13899

In [324]:
print("The top two eigenvalues are: ")
eigenvalue1 = w[0]
eigenvalue1Index = 0
eigenvalue2 = w[1]
eigenvalue2Index = 1
print(w)
print(eigenvalue1)
print(eigenvalue2)
for i in range(2, w.shape[0]):
    if(eigenvalue1 > eigenvalue2):
        if(w[i] > eigenvalue2):
            eigenvalue2 = w[i]
            eigenvalue2Index = i
    else:
        if(w[i] > eigenvalue1):
            eigenvalue1 = w[i]
            eigenvalue1Index = i

The top two eigenvalues are: 
[  3.20759437e-01   2.28455202e-01   1.70342288e-09]
0.320759437336
0.228455202209


The top 2 principal components are found by finding the top 2 eigenvalues and extracting those corresponding eigenvectors:

In [325]:
U = np.zeros(shape=(3,2))
U[:,0]=v[:,eigenvalue1Index]
U[:,1]=v[:,eigenvalue2Index]
print(U)

[[ 0.21388132 -0.96003226]
 [-0.8960249  -0.26641574]
 [-0.38909402  0.08579463]]


## #4

In [326]:
xtilda = np.matmul(U.transpose(), X)
# print("Feature vector x tilda:")
# print()
# print(xtilda)
xhat = np.matmul(U, xtilda)
# print()
# print("original data samples x hat:")
# print()
# print(xhat)

In [327]:
print(np.linalg.norm(xhat-X)**2)

8.95933314173e-32


## #5

In [328]:
# u1 = U[:,0]
# print(u1.transpose().shape)
# print(X.shape)
# xtilda = np.matmul(u1.transpose(), X)
# # print(xtilda.reshape(500, 1))
# print(xtilda.shape)
# # print(U[:,0].transpose().shape)
# xhat = np.matmul(U[:,0], xtilda)
# print(xhat.shape)

### Generation of Dataset #2

#### 1) generate fixed vector c

In [329]:
c = np.zeros(shape=(3,1))
mu, sigma = 0, 3 # mean and standard deviation
for i in range(c.shape[0]):
    c[i] = np.random.normal(mu, sigma, 1)
print("vector c:")
print(c)

X = np.zeros(shape=(3, 500))
for i in range(500):
    v1 = np.zeros(shape=(2,1))
    for j in range(v1.shape[0]):
        v1[j] = np.random.normal(mu, 1, 1)
    Av1 = np.matmul(A, v1)
    xi = Av1 + c
    X[0][i] = xi[0]
    X[1][i] = xi[1]
    X[2][i] = xi[2]
print(X.shape)
print(np.linalg.matrix_rank(X))

vector c:
[[ 1.83985051]
 [-2.03003243]
 [ 6.25568678]]
(3, 500)
3


### PCA, Centering, and Dataset #2

In [330]:
XXT = np.matmul(X, X.transpose())
w, v = np.linalg.eig(XXT)
print(v)
print(w)
print("The top two eigenvalues are: ")
eigenvalue1 = w[0]
eigenvalue1Index = 0
eigenvalue2 = w[1]
eigenvalue2Index = 1
for i in range(2, w.shape[0]):
    if(eigenvalue1 > eigenvalue2):
        if(w[i] > eigenvalue2):
            eigenvalue2 = w[i]
            eigenvalue2Index = i
    else:
        if(w[i] > eigenvalue1):
            eigenvalue1 = w[i]
            eigenvalue1Index = i
print(eigenvalue1Index)
print(eigenvalue2Index)

[[-0.2693045   0.9013613  -0.33915026]
 [ 0.29810375  0.41288529  0.860616  ]
 [-0.9157561  -0.13066579  0.37989105]]
[  2.33170910e+04   5.25407983e+00   9.49176697e+00]
The top two eigenvalues are: 
0
2


In [331]:
U[:,0]=v[:,eigenvalue1Index]
U[:,1]=v[:,eigenvalue2Index]
print(U)

[[-0.2693045  -0.33915026]
 [ 0.29810375  0.860616  ]
 [-0.9157561   0.37989105]]


In [332]:
UUT = np.matmul(U, U.transpose())
print(UUT.shape)
xhat = np.matmul(UUT, X)
print(np.linalg.norm(xhat-X)**2)
mean = X.mean(0)
# print(mean)
print(mean.shape)
# mean.shape = (mean.shape[0], 1)
print(X.shape)
centeredX = X-mean
print(centeredX.shape)
# X-mean

(3, 3)
5.25407982757
(500,)
(3, 500)
(3, 500)


In [333]:
w, v = np.linalg.eig(XXT)
print(v)
print(w)
print("The top two eigenvalues are: ")
eigenvalue1 = w[0]
eigenvalue1Index = 0
eigenvalue2 = w[1]
eigenvalue2Index = 1
for i in range(2, w.shape[0]):
    if(eigenvalue1 > eigenvalue2):
        if(w[i] > eigenvalue2):
            eigenvalue2 = w[i]
            eigenvalue2Index = i
    else:
        if(w[i] > eigenvalue1):
            eigenvalue1 = w[i]
            eigenvalue1Index = i
print(eigenvalue1Index)
print(eigenvalue2Index)
U[:,0]=v[:,eigenvalue1Index]
U[:,1]=v[:,eigenvalue2Index]
print(U)

[[-0.2693045   0.9013613  -0.33915026]
 [ 0.29810375  0.41288529  0.860616  ]
 [-0.9157561  -0.13066579  0.37989105]]
[  2.33170910e+04   5.25407983e+00   9.49176697e+00]
The top two eigenvalues are: 
0
2
[[-0.2693045  -0.33915026]
 [ 0.29810375  0.860616  ]
 [-0.9157561   0.37989105]]


In [334]:
UUT = np.matmul(U, U.transpose())
xhat = np.matmul(UUT, centeredX)+mean
print(np.linalg.norm(xhat-X)**2)

2857.86772561


## Generation of Dataset #3

In [335]:
N = 500
X = np.zeros(shape=(3,N))
v = np.zeros(shape=(2,1))
n = np.zeros(shape=(3,1)) # noise
for i in range(N):
    v[0] = np.random.normal(0, 1, 1)
    v[1] = np.random.normal(0, 1, 1)
    Av = np.matmul(A, v)
    n[0] = np.random.normal(0, 0.01, 1)
    n[1] = np.random.normal(0, 0.01, 1)
    n[2] = np.random.normal(0, 0.01, 1)
    x = Av+n
    X[0][i] = x[0]
    X[1][i] = x[1]
    X[2][i] = x[2]

In [336]:
# normalize X
for i in range(X.shape[1]):
    X[j][i] = (X[j][i])/np.linalg.norm(X[j][i])
print("Rank of normalized matrix: ", np.linalg.matrix_rank(X))
u, s, vT = np.linalg.svd(X)
print("Singular Values of normalized matrix: ", s)

3
[ 29.99297767  21.86344177  11.0639597 ]
